### ISSUE TITLE
[Task 1-3] "convert_to_scorch_format" can not consider singleton clusters.

### ISSUE THREAD

**Issue by yoongi0428** [emerging-welfare/case-2021-shared-task#3]
# Issue
https://github.com/emerging-welfare/case-2021-shared-task/blob/5d1e94a90aaee9f3a41b886e0beeb25597535b6d/task1/subtask3/code_sample.py#L41-L52

Official evaluation codes provieded in  ```task1/subtask3/code_sample.py``` uses "convert_to_scorch_format" to convert cluster results into scorch form.
However, Line 50 cannot preserve singleton cluster since it extracts nodes from links (or edges).
Since scorch extracts singleton from given nodes (all_events), this should be fixed.

This issue makes "MaxC" baseline (putting all in a basket) completely fails.

# Reproducible Example
docs = {'event_clusters': [[[1], [2], [3], [4], [5]], [[6], [7]]]}
links, events = convert_to_scorch_format(docs)

## Expected results
links = []
events = ['0_1', '0_2', '0_3', '0_4', '0_5', '1_6', '1_7']

## Current results
links = []
events = []

# Suggestion
Nodes should be extracted independently from links.
I'm providing one of possible solutions.

```python
def convert_to_scorch_format(docs, cluster_key="event_clusters"):
    # Merge all documents' clusters in a single list
    all_clusters = []
    all_events = []
    for idx, doc in enumerate(docs):
        for cluster in doc[cluster_key]:
            cluster_ids = [str(idx) + "_" + str(sent_id) for sent_id in cluster]
            all_clusters.append(cluster_ids)
            all_events = list(set(all_events + cluster_ids))

    all_links = sum([list(itertools.combinations(cluster,2)) for cluster in all_clusters],[])
    return all_links, all_events
```

**Comment by OsmanMutlu** [comment]
Thank you for the heads up, a very nice catch! We recently changed our metrics to CoNLL 2012 average score from Adjusted Rand Index and did not get the chance to evaluate the baselines yet.
